### ISSUE TITLE
Comparison to alternatives

### ISSUE THREAD

**Issue by rmacklin** [bibendi/feature_toggles#2]
Hi,

I came across this gem and thought it would be helpful if there was a comparison (e.g. in the README) to similar gems like [flipper](https://github.com/jnunemaker/flipper), [rollout](https://github.com/fetlife/rollout), etc, to help the community evaluate which dependency they might want to adopt.

If you disagree, feel free to close this issue - just figured I'd put it out there :)

**Comment by bibendi** [comment]
Hey!

There are a lot of gems similar to feature_toggles. Each of them solves the own problem. The primary cause of appearance this gem is a desire for simplicity. I think we all are smart to choose the right way without any instructions  :)
